# Generated by Django 2.2.5 on 2019-10-04 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_news_registtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='headimg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='userdetail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='registtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 15, 13, 10, 760868)),
        ),
    ]
