# Generated by Django 2.2.5 on 2019-10-04 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20191004_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='headimg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='registtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 16, 6, 57, 61633)),
        ),
    ]
